Repository prgrms-web-devcourse-final-project/WEB4_5_ServerSOS_BE, pull requests merged in 2025-06, with the labels that each got.

#176 프론트 버그 수정
  frontend/src/components/reservation/SeatMap.tsx
  frontend/src/pages/Join.tsx
  frontend/src/pages/ShowDetail.tsx
Labels: bug, refactor

#180 feat: 좌석 이슈 수정
  frontend/src/components/reservation/SeatMap.tsx
Labels: feat

#178 [FE] 게시글 조회수 보이게 설정
  frontend/src/pages/ShowDetail.tsx
Labels: feat

#187 [fix] cascade 설정
  backend/src/main/java/com/pickgo/domain/payment/entity/Payment.java
  backend/src/main/java/com/pickgo/domain/performance/area/area/entity/PerformanceArea.java
  backend/src/main/java/com/pickgo/domain/performance/area/seat/entity/ReservedSeat.java
  backend/src/main/java/com/pickgo/domain/performance/performance/entity/Performance.java
  backend/src/main/java/com/pickgo/domain/performance/performance/entity/PerformanceIntro.java
  backend/src/main/java/com/pickgo/domain/performance/performance/entity/PerformanceSession.java
  backend/src/main/java/com/pickgo/domain/post/post/entity/Post.java
  backend/src/main/java/com/pickgo/domain/post/review/entity/Review.java
  backend/src/main/java/com/pickgo/domain/post/review/entity/ReviewLike.java
  backend/src/main/java/com/pickgo/domain/reservation/entity/Reservation.java
Labels: bug

#188 [fix] DB delete on cascade 설정
  backend/src/main/java/com/pickgo/domain/payment/entity/Payment.java
  backend/src/main/java/com/pickgo/domain/performance/area/area/entity/PerformanceArea.java
  backend/src/main/java/com/pickgo/domain/performance/area/seat/entity/ReservedSeat.java
  backend/src/main/java/com/pickgo/domain/post/post/entity/Post.java
  backend/src/main/java/com/pickgo/domain/post/review/entity/Review.java
  backend/src/main/java/com/pickgo/domain/post/review/entity/ReviewLike.java
  backend/src/main/java/com/pickgo/domain/reservation/entity/Reservation.java
Labels: bug

#189 main <- develop 배포
  backend/src/main/java/com/pickgo/domain/payment/entity/Payment.java
  backend/src/main/java/com/pickgo/domain/performance/area/area/entity/PerformanceArea.java
  backend/src/main/java/com/pickgo/domain/performance/area/seat/entity/ReservedSeat.java
  backend/src/main/java/com/pickgo/domain/performance/performance/entity/Performance.java
  backend/src/main/java/com/pickgo/domain/performance/performance/entity/PerformanceIntro.java
  backend/src/main/java/com/pickgo/domain/performance/performance/entity/PerformanceSession.java
  backend/src/main/java/com/pickgo/domain/post/post/entity/Post.java
  backend/src/main/java/com/pickgo/domain/post/review/entity/Review.java
  backend/src/main/java/com/pickgo/domain/post/review/entity/ReviewLike.java
  backend/src/main/java/com/pickgo/domain/reservation/entity/Reservation.java
Labels: deploy

#192 docs: README.md 내용 추가
  README.md
Labels: doc
